version: 2

builds:
  - env:
    # Disable cgo to ensure static linking
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    binary: surge
    main: .
    ldflags:
      # -s and -w strip debug information to reduce binary size
      - -s -w 
      - -X github.com/surge-downloader/surge/cmd.Version={{.Version}}
      - -X github.com/surge-downloader/surge/cmd.BuildTime={{.Date}}

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

archives:

  # Windows zip, rest .tar.gz
  - formats: [ tar.gz ]
    format_overrides:
      - goos: windows
        formats: [ zip ]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    
    # Add LICENSE and README.md to archive
    files:
      - LICENSE
      - README.md

homebrew_casks:
  - name: surge
    repository:
      owner: surge-downloader
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    homepage: "https://github.com/surge-downloader/surge"
    description: "Surge is a blazing fast, open-source terminal (TUI) download manager built in Go."
    license: "MIT"
    hooks:
      post:
        # hack for macos to remove quarantine
        install: |
          if OS.mac?
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/surge"]
          end
